using System.Text;

namespace Plugin.Maui.HttpForge.Generator;

internal static class HttpForgeEmitter
{
    public static string Emit(ApiInterfaceModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Net.Http;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using Plugin.Maui.HttpForge;");
        builder.AppendLine();

        var clientName = model.InterfaceName + "_HttpForgeClient";
        var clientFullName = string.IsNullOrEmpty(model.Namespace)
            ? clientName
            : model.Namespace + "." + clientName;

        builder.Append("[assembly: Plugin.Maui.HttpForge.HttpForgeClient(typeof(")
            .Append(model.TypeFullName)
            .Append("), typeof(global::")
            .Append(clientFullName)
            .AppendLine("))]");
        builder.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("internal sealed class ").Append(clientName).Append(" : ").Append(model.TypeFullName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    private readonly HttpClient _client;");
        builder.AppendLine("    private readonly HttpForgeSettings _settings;");
        builder.AppendLine();
        builder.Append("    public ").Append(clientName).AppendLine("(HttpClient client, HttpForgeSettings settings)");
        builder.AppendLine("    {");
        builder.AppendLine("        _client = client;");
        builder.AppendLine("        _settings = settings;");
        builder.AppendLine("    }");

        foreach (var method in model.Methods.AsImmutableArray())
        {
            builder.AppendLine();
            EmitMethod(builder, method);
        }

        builder.AppendLine();
        builder.AppendLine("    [ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.AppendLine("    {");
        builder.Append("        HttpForgeClientRegistry.Register<").Append(model.TypeFullName).Append(">(static (client, settings) => new ").Append(clientName).AppendLine("(client, settings));");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitMethod(StringBuilder builder, ApiMethodModel method)
    {
        builder.Append("    public async ");
        builder.Append(GetReturnType(method));
        builder.Append(' ');
        builder.Append(method.Name);
        builder.Append('(');
        builder.Append(string.Join(", ", method.Parameters.AsImmutableArray().Select(FormatParameter)));
        builder.AppendLine(")");
        builder.AppendLine("    {");

        var pathParams = method.Parameters.AsImmutableArray().Where(p => p.Kind == ParameterKinds.Path).ToArray();
        var queryParams = method.Parameters.AsImmutableArray().Where(p => p.Kind == ParameterKinds.Query).ToArray();
        var body = method.Parameters.AsImmutableArray().FirstOrDefault(p => p.Kind == ParameterKinds.Body);
        var cancel = method.Parameters.AsImmutableArray().FirstOrDefault(p => p.Kind == ParameterKinds.Cancel);
        var cancelExpr = cancel.Name is { Length: > 0 } ? cancel.Name : "default";

        builder.Append("        var __path = ");
        builder.Append(BuildPathExpression(method.Path, pathParams));
        builder.AppendLine(";");

        if (queryParams.Length > 0)
        {
            builder.AppendLine("        var __query = new HttpForgeQueryBuilder();");
            foreach (var parameter in queryParams)
            {
                builder.Append("        __query.Add(\"").Append(Escape(parameter.WireName)).Append("\", ").Append(parameter.Name).AppendLine(");");
            }

            builder.AppendLine("        __path += __query.ToString();");
        }

        builder.Append("        using var __request = new HttpRequestMessage(new HttpMethod(\"").Append(method.HttpMethod).AppendLine("\"), __path);");

        foreach (var header in method.Headers.AsImmutableArray())
        {
            builder.Append("        HttpForgeInvoker.AddStaticHeader(__request, \"").Append(Escape(header)).AppendLine("\");");
        }

        foreach (var parameter in method.Parameters.AsImmutableArray().Where(p => p.Kind == ParameterKinds.Header))
        {
            builder.Append("        HttpForgeInvoker.AddHeader(__request, \"").Append(Escape(parameter.HeaderName ?? parameter.WireName)).Append("\", ").Append(parameter.Name).AppendLine(");");
        }

        if (method.IsMultipart)
        {
            builder.AppendLine("        var __content = new MultipartFormDataContent();");
            foreach (var parameter in method.Parameters.AsImmutableArray().Where(p => p.Kind == ParameterKinds.Multipart))
            {
                builder.Append("        HttpForgeMultipart.AddPart(__content, \"").Append(Escape(parameter.WireName)).Append("\", ").Append(parameter.Name).AppendLine(");");
            }

            builder.AppendLine("        __request.Content = __content;");
        }
        else if (body.Name is { Length: > 0 })
        {
            builder.Append("        __request.Content = await _settings.ContentSerializer.ToHttpContentAsync(").Append(body.Name).Append(", ").Append(cancelExpr).AppendLine(").ConfigureAwait(false);");
        }

        builder.Append("        ");
        builder.AppendLine(GetInvokeStatement(method, cancelExpr));
        builder.AppendLine("    }");
    }

    private static string GetReturnType(ApiMethodModel method) => method.ReturnKind switch
    {
        ReturnKinds.Void => "System.Threading.Tasks.Task",
        ReturnKinds.HttpResponse => "System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>",
        ReturnKinds.ApiResponse => "System.Threading.Tasks.Task<Plugin.Maui.HttpForge.IApiResponse<" + method.ResponseType + ">>",
        _ => "System.Threading.Tasks.Task<" + method.ResponseType + ">"
    };

    private static string GetInvokeStatement(ApiMethodModel method, string cancelExpr) => method.ReturnKind switch
    {
        ReturnKinds.Void => $"await HttpForgeInvoker.SendAsync(_client, __request, _settings, {cancelExpr}).ConfigureAwait(false);",
        ReturnKinds.ApiResponse => $"return await HttpForgeInvoker.SendApiResponseAsync<{method.ResponseType}>(_client, __request, _settings, {cancelExpr}).ConfigureAwait(false);",
        _ => $"return await HttpForgeInvoker.SendAsync<{method.ResponseType}>(_client, __request, _settings, {cancelExpr}).ConfigureAwait(false);"
    };

    private static string FormatParameter(ParameterModel parameter)
    {
        var result = parameter.TypeFullName + " " + parameter.Name;
        if (parameter.HasDefault)
            result += " = " + parameter.DefaultLiteral;
        return result;
    }

    private static string BuildPathExpression(string path, ParameterModel[] pathParams)
    {
        var remaining = path;
        var parts = new List<string>();
        while (remaining.Length > 0)
        {
            var start = remaining.IndexOf('{');
            if (start < 0)
            {
                parts.Add(Quote(remaining));
                break;
            }

            if (start > 0)
                parts.Add(Quote(remaining.Substring(0, start)));

            var end = remaining.IndexOf('}', start);
            if (end < 0)
            {
                parts.Add(Quote(remaining.Substring(start)));
                break;
            }

            var token = remaining.Substring(start + 1, end - start - 1);
            var parameter = pathParams.FirstOrDefault(p => p.WireName == token);
            parts.Add("HttpForgeInvoker.FormatPathValue(" + (parameter.Name ?? "null") + ")");
            remaining = remaining.Substring(end + 1);
        }

        if (parts.Count == 0)
            return "\"/\"";

        return string.Join(" + ", parts);
    }

    private static string Quote(string value) => "\"" + Escape(value) + "\"";

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
